INSERT INTO faculties (id, name, website, email, phone, address, info)
VALUES (1, 'Faculty of Biology', 'bioweb.lnu.edu.ua', 'biolog@lnu.edu.ua', '274-03-72, 239-41-53',
        'Mykhaila Hrushevskoho Street, 4, Lviv, 79005, Ukraine, 79005', 'Faculty of Biology is ...'),
       (2, 'Faculty of Geography', 'geography.lnu.edu.ua', 'geodekanat@gmail.com', '239-41-62, 272-26-44',
        'Address: Doroshenka Street, 41, Lviv, 79000, Ukraine', 'Faculty of Geography is ...'),
       (3, 'Faculty of Geology', 'geology.lnu.edu.ua', 'decanat.geology@ukr.net', '261-60-56, 239-41-56',
        'Mykhaila Hryshevskoho Street, 4, Lviv, 79005, Ukraine, 79005', 'Faculty of Geology is ...'),
       (4, 'Faculty of Economics', 'econom.lnu.edu.ua', 'edean@lnu.edu.ua', '239-41-68',
        'Svobody Avenue, 18, Lviv, 79008, Ukraine, 79008', 'Faculty of Economics is ...'),
       (5, 'Faculty of Electronics and computer technologies', 'electronics.lnu.edu.ua',
        'electronics.faculty@lnu.edu.ua', '261-14-91, 239-47-24, 239-41-82',
        'Drahomanova Street, 50, Lviv, 79005, Ukraine', 'Faculty of Electronics and computer technologies is ...'),
       (6, 'Faculty of Journalism', 'journ.lnu.edu.ua', 'journft@lnu.edu.ua', '239-47-51',
        'Henerala Chuprynky Street, 49, Lviv, 79044, Україна', 'Faculty of Journalism is ...'),
       (7, 'Faculty of Foreign Languages', 'lingua.lnu.edu.ua', 'lingua.faculty@lnu.edu.ua', '239-47-16',
        'Universytetska Street 1/415, Lviv, 79000, Ukraine', 'Faculty of Foreign Languages is ...'),
       (8, 'Faculty of History', 'clio.lnu.edu.ua', 'clio@lnu.edu.ua', '261-03-28',
        'Universytetska Street, 1, Lviv, 79000, Ukraine', 'Faculty of History is ...'),
       (9, 'Faculty of Culture and Arts', 'kultart.lnu.edu.ua', 'fkultart@lnu.edu.ua', '239-41-97',
        'Valova Street,18, Lviv, 79008, Ukraine', 'Faculty of Culture and Arts is ...'),
       (10, 'Faculty of Mechanics and Mathematics', 'www.mmf.lnu.edu.ua', 'dmmf@lnu.edu.ua',
        '260-00-09, 239-41-74, 239-47-43', 'Universytetska Street, 1, Lviv, 79000, Ukraine',
        'Faculty of Mechanics and Mathematics is ...'),
       (11, 'Faculty of International Relations', 'intrel.lnu.edu.ua', 'intrel.faculty@lnu.edu.ua', '255-43-17',
        'Sichovykh Striltsiv Street, 19, Lviv, 79000, Ukraine, 79000', 'Faculty of International Relations is ...'),
       (12, 'Faculty of Pedagogical Education', 'pedagogy.lnu.edu.ua', 'pedosv.fakultet@ukr.net', '239-42-30',
        'Tuhan-Baranovskoho Street, 7, Lviv, 79000, Ukraine', 'Faculty of Pedagogical Education is ...'),
       (13, 'Faculty of Applied Mathematics and Informatics', 'ami.lnu.edu.ua', 'ami@lnu.edu.ua',
        '274-01-80, 239-41-86', 'Universytetska Street 1, Lviv, 79000, Ukraine',
        'Faculty of Applied Mathematics and Informatics is ...'),
       (14, 'Faculty of Financial Management and Business', 'financial.lnu.edu.ua', 'financial.faculty@lnu.edu.ua',
        '235-64-50, 235-86-54', 'Kopernyka Street, 3, Lviv, 79000, Ukraine',
        'Faculty of Financial Management and Business is ...'),
       (15, 'Faculty of Physics', 'physics.lnu.edu.ua', 'fiz_dekanat@lnu.edu.ua', '272-70-64',
        'Kyryla i Mefodiya Street, 8, Lviv, 79005, Ukraine', 'Faculty of Physics is ...'),
       (16, 'Faculty of Philology', 'philology.lnu.edu.ua', 'filologylnu@gmail.com', '255-41-33, 239-41-58, 239-41-88',
        'Universytetska Street, 1, room 232, Lviv, 79000, Ukraine', 'Faculty of Philology is ...'),
       (17, 'Faculty of Philosophy', 'filos.lnu.edu.ua', 'dfilos@lnu.edu.ua', '239-45-79',
        'Universytetska Street, 1, Lviv, 79001, Ukraine', 'Faculty of Philosophy is ...'),
       (18, 'Faculty of Chemistry', 'chem.lnu.edu.ua', 'chemdek@lnu.edu.ua', '260-03-91, 239-45-10',
        'Kyryla I Mefodiya, 6, Lviv, 79005, Ukraine', 'Faculty of Chemistry is ...'),
       (19, 'Faculty of Law', 'law.lnu.edu.ua', 'law.faculty@lnu.edu.ua', '239-41-02',
        'вул. Січових Стрільців, 14, м. Львів, 79000', 'Faculty of Law is ...');
SELECT setval('faculties_id_seq', 19);